#!/bin/sh

outputPath=~/Desktop/musicoutput;
sourcePath=~/Desktop/musics;

for file in $sourcePath/*; do
    fileName=$(basename ${file});
    filenameNoExt=$(echo $fileName | cut -f 1 -d '.' | cut -d '】' -f 2-);
    outputFile="${outputPath}/${filenameNoExt}.aac";
    echo $fileName;
    echo $outputFile;
    ffmpeg -i $file  -b:a 24K $outputFile;
    test $? -gt 128 && break;
done
